name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'    
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: test
      run: cd test && go test
