name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.25

    - name: format check
      run: terraform fmt -check -diff -recursive

    - name: validate
      run: cd test/fixtures/default && terraform init && terraform validate

    - name: Release
      env:
        GITHUB_TOKEN: ${RELEASE_GITHUB_TOKEN}
      run: npx release-it -- --dry-run minor --ci
